name: "Build and lint"

on:
  push:
    branches:
      - main
      - master
    
      
jobs:

  helm:
    name: helm-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Helm chart
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.23.6
          helm: 2.17.0
          helmv3: 3.6.0
          command: |
            helmv3 template . | kubeval --strict --kubernetes-version 1.23.6 --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master
